//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//     Support: http://www.cnblogs.com/huxj
//     Website: http://www.ITdos.com/
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

	/// <summary>
	/// 实体类Biz_CTCoach 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class Biz_CTCoach : Entity 
	{
		public Biz_CTCoach():base("Biz_CTCoach") {}

		#region Model
		private Guid _ID;
        private bool _isAttached;
        private string _Sex;
		private string _NickName;
		private string _MobilePhone;
		private string _QQ;
		private string _Email;
		private string _IDNumber;
		private string _RealName;
		private string _DocNumber;
		private string _DocExpiryDate;
		private string _Province;
		private string _City;
		private string _Town;
		private DateTime _CreateTime;
		private string _WeChat;
		private string _DrivingSchool;
		private bool _IsCertification;
		private bool _IsBind;
		private string _AllowCoachCar;
		private string _Subject2Hours;
		private string _Subject3Hours;
		private string _HeadImg;
		private string _CourseCustom;
		private string _IDPhotos;
		private string _SelfInfo;
		private string _DrivingType;
        /// <summary>
        /// 
        /// </summary>
        public bool isAttached
        {
            get { return _isAttached; }
            set
            {
                this.OnPropertyValueChange(_.isAttached, _isAttached, value);
                this._isAttached = value;
            }
        }
		/// <summary>
		/// 
		/// </summary>
		public Guid ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NickName
		{
			get{ return _NickName; }
			set
			{
				this.OnPropertyValueChange(_.NickName,_NickName,value);
				this._NickName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MobilePhone
		{
			get{ return _MobilePhone; }
			set
			{
				this.OnPropertyValueChange(_.MobilePhone,_MobilePhone,value);
				this._MobilePhone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QQ
		{
			get{ return _QQ; }
			set
			{
				this.OnPropertyValueChange(_.QQ,_QQ,value);
				this._QQ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IDNumber
		{
			get{ return _IDNumber; }
			set
			{
				this.OnPropertyValueChange(_.IDNumber,_IDNumber,value);
				this._IDNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RealName
		{
			get{ return _RealName; }
			set
			{
				this.OnPropertyValueChange(_.RealName,_RealName,value);
				this._RealName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DocNumber
		{
			get{ return _DocNumber; }
			set
			{
				this.OnPropertyValueChange(_.DocNumber,_DocNumber,value);
				this._DocNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DocExpiryDate
		{
			get{ return _DocExpiryDate; }
			set
			{
				this.OnPropertyValueChange(_.DocExpiryDate,_DocExpiryDate,value);
				this._DocExpiryDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Province
		{
			get{ return _Province; }
			set
			{
				this.OnPropertyValueChange(_.Province,_Province,value);
				this._Province=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string City
		{
			get{ return _City; }
			set
			{
				this.OnPropertyValueChange(_.City,_City,value);
				this._City=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Town
		{
			get{ return _Town; }
			set
			{
				this.OnPropertyValueChange(_.Town,_Town,value);
				this._Town=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string WeChat
		{
			get{ return _WeChat; }
			set
			{
				this.OnPropertyValueChange(_.WeChat,_WeChat,value);
				this._WeChat=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DrivingSchool
		{
			get{ return _DrivingSchool; }
			set
			{
				this.OnPropertyValueChange(_.DrivingSchool,_DrivingSchool,value);
				this._DrivingSchool=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsCertification
		{
			get{ return _IsCertification; }
			set
			{
				this.OnPropertyValueChange(_.IsCertification,_IsCertification,value);
				this._IsCertification=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsBind
		{
			get{ return _IsBind; }
			set
			{
				this.OnPropertyValueChange(_.IsBind,_IsBind,value);
				this._IsBind=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AllowCoachCar
		{
			get{ return _AllowCoachCar; }
			set
			{
				this.OnPropertyValueChange(_.AllowCoachCar,_AllowCoachCar,value);
				this._AllowCoachCar=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject2Hours
		{
			get{ return _Subject2Hours; }
			set
			{
				this.OnPropertyValueChange(_.Subject2Hours,_Subject2Hours,value);
				this._Subject2Hours=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject3Hours
		{
			get{ return _Subject3Hours; }
			set
			{
				this.OnPropertyValueChange(_.Subject3Hours,_Subject3Hours,value);
				this._Subject3Hours=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HeadImg
		{
			get{ return _HeadImg; }
			set
			{
				this.OnPropertyValueChange(_.HeadImg,_HeadImg,value);
				this._HeadImg=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CourseCustom
		{
			get{ return _CourseCustom; }
			set
			{
				this.OnPropertyValueChange(_.CourseCustom,_CourseCustom,value);
				this._CourseCustom=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IDPhotos
		{
			get{ return _IDPhotos; }
			set
			{
				this.OnPropertyValueChange(_.IDPhotos,_IDPhotos,value);
				this._IDPhotos=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SelfInfo
		{
			get{ return _SelfInfo; }
			set
			{
				this.OnPropertyValueChange(_.SelfInfo,_SelfInfo,value);
				this._SelfInfo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DrivingType
		{
			get{ return _DrivingType; }
			set
			{
				this.OnPropertyValueChange(_.DrivingType,_DrivingType,value);
				this._DrivingType=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Sex,
				_.NickName,
				_.MobilePhone,
				_.QQ,
				_.Email,
				_.IDNumber,
				_.RealName,
				_.DocNumber,
				_.DocExpiryDate,
				_.Province,
				_.City,
				_.Town,
				_.CreateTime,
				_.WeChat,
				_.DrivingSchool,
				_.IsCertification,
				_.IsBind,
				_.AllowCoachCar,
				_.Subject2Hours,
				_.Subject3Hours,
				_.HeadImg,
				_.CourseCustom,
				_.IDPhotos,
				_.SelfInfo,
				_.DrivingType};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Sex,
				this._NickName,
				this._MobilePhone,
				this._QQ,
				this._Email,
				this._IDNumber,
				this._RealName,
				this._DocNumber,
				this._DocExpiryDate,
				this._Province,
				this._City,
				this._Town,
				this._CreateTime,
				this._WeChat,
				this._DrivingSchool,
				this._IsCertification,
				this._IsBind,
				this._AllowCoachCar,
				this._Subject2Hours,
				this._Subject3Hours,
				this._HeadImg,
				this._CourseCustom,
				this._IDPhotos,
				this._SelfInfo,
				this._DrivingType};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._ID = DataUtils.ConvertValue<Guid>(reader["ID"]);
			this._Sex = DataUtils.ConvertValue<string>(reader["Sex"]);
			this._NickName = DataUtils.ConvertValue<string>(reader["NickName"]);
			this._MobilePhone = DataUtils.ConvertValue<string>(reader["MobilePhone"]);
			this._QQ = DataUtils.ConvertValue<string>(reader["QQ"]);
			this._Email = DataUtils.ConvertValue<string>(reader["Email"]);
			this._IDNumber = DataUtils.ConvertValue<string>(reader["IDNumber"]);
			this._RealName = DataUtils.ConvertValue<string>(reader["RealName"]);
			this._DocNumber = DataUtils.ConvertValue<string>(reader["DocNumber"]);
			this._DocExpiryDate = DataUtils.ConvertValue<string>(reader["DocExpiryDate"]);
			this._Province = DataUtils.ConvertValue<string>(reader["Province"]);
			this._City = DataUtils.ConvertValue<string>(reader["City"]);
			this._Town = DataUtils.ConvertValue<string>(reader["Town"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._WeChat = DataUtils.ConvertValue<string>(reader["WeChat"]);
			this._DrivingSchool = DataUtils.ConvertValue<string>(reader["DrivingSchool"]);
			this._IsCertification = DataUtils.ConvertValue<bool>(reader["IsCertification"]);
			this._IsBind = DataUtils.ConvertValue<bool>(reader["IsBind"]);
			this._AllowCoachCar = DataUtils.ConvertValue<string>(reader["AllowCoachCar"]);
			this._Subject2Hours = DataUtils.ConvertValue<string>(reader["Subject2Hours"]);
			this._Subject3Hours = DataUtils.ConvertValue<string>(reader["Subject3Hours"]);
			this._HeadImg = DataUtils.ConvertValue<string>(reader["HeadImg"]);
			this._CourseCustom = DataUtils.ConvertValue<string>(reader["CourseCustom"]);
			this._IDPhotos = DataUtils.ConvertValue<string>(reader["IDPhotos"]);
			this._SelfInfo = DataUtils.ConvertValue<string>(reader["SelfInfo"]);
			this._DrivingType = DataUtils.ConvertValue<string>(reader["DrivingType"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._ID = DataUtils.ConvertValue<Guid>(row["ID"]);
			this._Sex = DataUtils.ConvertValue<string>(row["Sex"]);
			this._NickName = DataUtils.ConvertValue<string>(row["NickName"]);
			this._MobilePhone = DataUtils.ConvertValue<string>(row["MobilePhone"]);
			this._QQ = DataUtils.ConvertValue<string>(row["QQ"]);
			this._Email = DataUtils.ConvertValue<string>(row["Email"]);
			this._IDNumber = DataUtils.ConvertValue<string>(row["IDNumber"]);
			this._RealName = DataUtils.ConvertValue<string>(row["RealName"]);
			this._DocNumber = DataUtils.ConvertValue<string>(row["DocNumber"]);
			this._DocExpiryDate = DataUtils.ConvertValue<string>(row["DocExpiryDate"]);
			this._Province = DataUtils.ConvertValue<string>(row["Province"]);
			this._City = DataUtils.ConvertValue<string>(row["City"]);
			this._Town = DataUtils.ConvertValue<string>(row["Town"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._WeChat = DataUtils.ConvertValue<string>(row["WeChat"]);
			this._DrivingSchool = DataUtils.ConvertValue<string>(row["DrivingSchool"]);
			this._IsCertification = DataUtils.ConvertValue<bool>(row["IsCertification"]);
			this._IsBind = DataUtils.ConvertValue<bool>(row["IsBind"]);
			this._AllowCoachCar = DataUtils.ConvertValue<string>(row["AllowCoachCar"]);
			this._Subject2Hours = DataUtils.ConvertValue<string>(row["Subject2Hours"]);
			this._Subject3Hours = DataUtils.ConvertValue<string>(row["Subject3Hours"]);
			this._HeadImg = DataUtils.ConvertValue<string>(row["HeadImg"]);
			this._CourseCustom = DataUtils.ConvertValue<string>(row["CourseCustom"]);
			this._IDPhotos = DataUtils.ConvertValue<string>(row["IDPhotos"]);
			this._SelfInfo = DataUtils.ConvertValue<string>(row["SelfInfo"]);
			this._DrivingType = DataUtils.ConvertValue<string>(row["DrivingType"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
            public readonly static Field isAttached = new Field("*", "Biz_CTCoach");
            /// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Biz_CTCoach");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Biz_CTCoach","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","Biz_CTCoach","Sex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NickName = new Field("NickName","Biz_CTCoach","NickName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MobilePhone = new Field("MobilePhone","Biz_CTCoach","MobilePhone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QQ = new Field("QQ","Biz_CTCoach","QQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","Biz_CTCoach","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IDNumber = new Field("IDNumber","Biz_CTCoach","IDNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RealName = new Field("RealName","Biz_CTCoach","RealName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DocNumber = new Field("DocNumber","Biz_CTCoach","DocNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DocExpiryDate = new Field("DocExpiryDate","Biz_CTCoach","DocExpiryDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Province = new Field("Province","Biz_CTCoach","Province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City","Biz_CTCoach","City");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Town = new Field("Town","Biz_CTCoach","Town");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Biz_CTCoach","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WeChat = new Field("WeChat","Biz_CTCoach","WeChat");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DrivingSchool = new Field("DrivingSchool","Biz_CTCoach","DrivingSchool");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsCertification = new Field("IsCertification","Biz_CTCoach","IsCertification");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsBind = new Field("IsBind","Biz_CTCoach","IsBind");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllowCoachCar = new Field("AllowCoachCar","Biz_CTCoach","AllowCoachCar");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject2Hours = new Field("Subject2Hours","Biz_CTCoach","Subject2Hours");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject3Hours = new Field("Subject3Hours","Biz_CTCoach","Subject3Hours");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HeadImg = new Field("HeadImg","Biz_CTCoach","HeadImg");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CourseCustom = new Field("CourseCustom","Biz_CTCoach","CourseCustom");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IDPhotos = new Field("IDPhotos","Biz_CTCoach","IDPhotos");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SelfInfo = new Field("SelfInfo","Biz_CTCoach","SelfInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DrivingType = new Field("DrivingType","Biz_CTCoach","DrivingType");
		}
		#endregion


	}
}

