//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//     Support: http://www.cnblogs.com/huxj
//     Website: http://www.ITdos.com/
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

	/// <summary>
	/// 实体类Biz_CTCourse 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class Biz_CTCourse : Entity 
	{
		public Biz_CTCourse():base("Biz_CTCourse") {}

		#region Model
		private Guid _ID;
		private Guid _PubCoachId;
		private Guid? _CoachId;
		private string _Subject;
		private string _SubjectValue;
		private string _Date;
		private string _Week;
		private string _StartTime;
		private string _EndTime;
		private Guid? _CarId;
		private Guid? _TrainPlaceId;
		private int? _AllowStu;
		private int _State;
		/// <summary>
		/// 
		/// </summary>
		public Guid ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid PubCoachId
		{
			get{ return _PubCoachId; }
			set
			{
				this.OnPropertyValueChange(_.PubCoachId,_PubCoachId,value);
				this._PubCoachId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CoachId
		{
			get{ return _CoachId; }
			set
			{
				this.OnPropertyValueChange(_.CoachId,_CoachId,value);
				this._CoachId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject
		{
			get{ return _Subject; }
			set
			{
				this.OnPropertyValueChange(_.Subject,_Subject,value);
				this._Subject=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SubjectValue
		{
			get{ return _SubjectValue; }
			set
			{
				this.OnPropertyValueChange(_.SubjectValue,_SubjectValue,value);
				this._SubjectValue=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Date
		{
			get{ return _Date; }
			set
			{
				this.OnPropertyValueChange(_.Date,_Date,value);
				this._Date=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Week
		{
			get{ return _Week; }
			set
			{
				this.OnPropertyValueChange(_.Week,_Week,value);
				this._Week=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StartTime
		{
			get{ return _StartTime; }
			set
			{
				this.OnPropertyValueChange(_.StartTime,_StartTime,value);
				this._StartTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string EndTime
		{
			get{ return _EndTime; }
			set
			{
				this.OnPropertyValueChange(_.EndTime,_EndTime,value);
				this._EndTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CarId
		{
			get{ return _CarId; }
			set
			{
				this.OnPropertyValueChange(_.CarId,_CarId,value);
				this._CarId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? TrainPlaceId
		{
			get{ return _TrainPlaceId; }
			set
			{
				this.OnPropertyValueChange(_.TrainPlaceId,_TrainPlaceId,value);
				this._TrainPlaceId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AllowStu
		{
			get{ return _AllowStu; }
			set
			{
				this.OnPropertyValueChange(_.AllowStu,_AllowStu,value);
				this._AllowStu=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.PubCoachId,
				_.CoachId,
				_.Subject,
				_.SubjectValue,
				_.Date,
				_.Week,
				_.StartTime,
				_.EndTime,
				_.CarId,
				_.TrainPlaceId,
				_.AllowStu,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._PubCoachId,
				this._CoachId,
				this._Subject,
				this._SubjectValue,
				this._Date,
				this._Week,
				this._StartTime,
				this._EndTime,
				this._CarId,
				this._TrainPlaceId,
				this._AllowStu,
				this._State};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._ID = DataUtils.ConvertValue<Guid>(reader["ID"]);
			this._PubCoachId = DataUtils.ConvertValue<Guid>(reader["PubCoachId"]);
			this._CoachId = DataUtils.ConvertValue<Guid?>(reader["CoachId"]);
			this._Subject = DataUtils.ConvertValue<string>(reader["Subject"]);
			this._SubjectValue = DataUtils.ConvertValue<string>(reader["SubjectValue"]);
			this._Date = DataUtils.ConvertValue<string>(reader["Date"]);
			this._Week = DataUtils.ConvertValue<string>(reader["Week"]);
			this._StartTime = DataUtils.ConvertValue<string>(reader["StartTime"]);
			this._EndTime = DataUtils.ConvertValue<string>(reader["EndTime"]);
			this._CarId = DataUtils.ConvertValue<Guid?>(reader["CarId"]);
			this._TrainPlaceId = DataUtils.ConvertValue<Guid?>(reader["TrainPlaceId"]);
			this._AllowStu = DataUtils.ConvertValue<int?>(reader["AllowStu"]);
			this._State = DataUtils.ConvertValue<int>(reader["State"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._ID = DataUtils.ConvertValue<Guid>(row["ID"]);
			this._PubCoachId = DataUtils.ConvertValue<Guid>(row["PubCoachId"]);
			this._CoachId = DataUtils.ConvertValue<Guid?>(row["CoachId"]);
			this._Subject = DataUtils.ConvertValue<string>(row["Subject"]);
			this._SubjectValue = DataUtils.ConvertValue<string>(row["SubjectValue"]);
			this._Date = DataUtils.ConvertValue<string>(row["Date"]);
			this._Week = DataUtils.ConvertValue<string>(row["Week"]);
			this._StartTime = DataUtils.ConvertValue<string>(row["StartTime"]);
			this._EndTime = DataUtils.ConvertValue<string>(row["EndTime"]);
			this._CarId = DataUtils.ConvertValue<Guid?>(row["CarId"]);
			this._TrainPlaceId = DataUtils.ConvertValue<Guid?>(row["TrainPlaceId"]);
			this._AllowStu = DataUtils.ConvertValue<int?>(row["AllowStu"]);
			this._State = DataUtils.ConvertValue<int>(row["State"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Biz_CTCourse");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Biz_CTCourse","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PubCoachId = new Field("PubCoachId","Biz_CTCourse","PubCoachId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CoachId = new Field("CoachId","Biz_CTCourse","CoachId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject = new Field("Subject","Biz_CTCourse","Subject");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjectValue = new Field("SubjectValue","Biz_CTCourse","SubjectValue");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Date = new Field("Date","Biz_CTCourse","Date");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Week = new Field("Week","Biz_CTCourse","Week");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime","Biz_CTCourse","StartTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime","Biz_CTCourse","EndTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CarId = new Field("CarId","Biz_CTCourse","CarId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TrainPlaceId = new Field("TrainPlaceId","Biz_CTCourse","TrainPlaceId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllowStu = new Field("AllowStu","Biz_CTCourse","AllowStu");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","Biz_CTCourse","State");
		}
		#endregion


	}
}

