//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//     Support: http://www.cnblogs.com/huxj
//     Website: http://www.ITdos.com/
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

	/// <summary>
	/// 实体类Biz_CTCourseOrder 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class Biz_CTCourseOrder : Entity 
	{
		public Biz_CTCourseOrder():base("Biz_CTCourseOrder") {}

		#region Model
		private Guid _ID;
		private string _OrderTitle;
		private string _OrderDate;
		private Guid? _TrainPlaceId;
		private string _TrainPlaceAddress;
		private string _TrainPlaceName;
		private Guid? _CarId;
		private string _BrandModel;
		private string _CarType;
		private string _PlateNumber;
		private Guid _StudentId;
		private Guid? _CourseId;
		private DateTime _CreateTime;
		private string _RealName;
		private string _MobilePhone;
		private int _State;
		private int _Hours;
		private string _Remark;
		private string _Evaluate;
		/// <summary>
		/// 
		/// </summary>
		public Guid ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string OrderTitle
		{
			get{ return _OrderTitle; }
			set
			{
				this.OnPropertyValueChange(_.OrderTitle,_OrderTitle,value);
				this._OrderTitle=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string OrderDate
		{
			get{ return _OrderDate; }
			set
			{
				this.OnPropertyValueChange(_.OrderDate,_OrderDate,value);
				this._OrderDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? TrainPlaceId
		{
			get{ return _TrainPlaceId; }
			set
			{
				this.OnPropertyValueChange(_.TrainPlaceId,_TrainPlaceId,value);
				this._TrainPlaceId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TrainPlaceAddress
		{
			get{ return _TrainPlaceAddress; }
			set
			{
				this.OnPropertyValueChange(_.TrainPlaceAddress,_TrainPlaceAddress,value);
				this._TrainPlaceAddress=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TrainPlaceName
		{
			get{ return _TrainPlaceName; }
			set
			{
				this.OnPropertyValueChange(_.TrainPlaceName,_TrainPlaceName,value);
				this._TrainPlaceName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CarId
		{
			get{ return _CarId; }
			set
			{
				this.OnPropertyValueChange(_.CarId,_CarId,value);
				this._CarId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string BrandModel
		{
			get{ return _BrandModel; }
			set
			{
				this.OnPropertyValueChange(_.BrandModel,_BrandModel,value);
				this._BrandModel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CarType
		{
			get{ return _CarType; }
			set
			{
				this.OnPropertyValueChange(_.CarType,_CarType,value);
				this._CarType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PlateNumber
		{
			get{ return _PlateNumber; }
			set
			{
				this.OnPropertyValueChange(_.PlateNumber,_PlateNumber,value);
				this._PlateNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid StudentId
		{
			get{ return _StudentId; }
			set
			{
				this.OnPropertyValueChange(_.StudentId,_StudentId,value);
				this._StudentId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CourseId
		{
			get{ return _CourseId; }
			set
			{
				this.OnPropertyValueChange(_.CourseId,_CourseId,value);
				this._CourseId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RealName
		{
			get{ return _RealName; }
			set
			{
				this.OnPropertyValueChange(_.RealName,_RealName,value);
				this._RealName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MobilePhone
		{
			get{ return _MobilePhone; }
			set
			{
				this.OnPropertyValueChange(_.MobilePhone,_MobilePhone,value);
				this._MobilePhone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Hours
		{
			get{ return _Hours; }
			set
			{
				this.OnPropertyValueChange(_.Hours,_Hours,value);
				this._Hours=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Evaluate
		{
			get{ return _Evaluate; }
			set
			{
				this.OnPropertyValueChange(_.Evaluate,_Evaluate,value);
				this._Evaluate=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.OrderTitle,
				_.OrderDate,
				_.TrainPlaceId,
				_.TrainPlaceAddress,
				_.TrainPlaceName,
				_.CarId,
				_.BrandModel,
				_.CarType,
				_.PlateNumber,
				_.StudentId,
				_.CourseId,
				_.CreateTime,
				_.RealName,
				_.MobilePhone,
				_.State,
				_.Hours,
				_.Remark,
				_.Evaluate};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._OrderTitle,
				this._OrderDate,
				this._TrainPlaceId,
				this._TrainPlaceAddress,
				this._TrainPlaceName,
				this._CarId,
				this._BrandModel,
				this._CarType,
				this._PlateNumber,
				this._StudentId,
				this._CourseId,
				this._CreateTime,
				this._RealName,
				this._MobilePhone,
				this._State,
				this._Hours,
				this._Remark,
				this._Evaluate};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._ID = DataUtils.ConvertValue<Guid>(reader["ID"]);
			this._OrderTitle = DataUtils.ConvertValue<string>(reader["OrderTitle"]);
			this._OrderDate = DataUtils.ConvertValue<string>(reader["OrderDate"]);
			this._TrainPlaceId = DataUtils.ConvertValue<Guid?>(reader["TrainPlaceId"]);
			this._TrainPlaceAddress = DataUtils.ConvertValue<string>(reader["TrainPlaceAddress"]);
			this._TrainPlaceName = DataUtils.ConvertValue<string>(reader["TrainPlaceName"]);
			this._CarId = DataUtils.ConvertValue<Guid?>(reader["CarId"]);
			this._BrandModel = DataUtils.ConvertValue<string>(reader["BrandModel"]);
			this._CarType = DataUtils.ConvertValue<string>(reader["CarType"]);
			this._PlateNumber = DataUtils.ConvertValue<string>(reader["PlateNumber"]);
			this._StudentId = DataUtils.ConvertValue<Guid>(reader["StudentId"]);
			this._CourseId = DataUtils.ConvertValue<Guid?>(reader["CourseId"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._RealName = DataUtils.ConvertValue<string>(reader["RealName"]);
			this._MobilePhone = DataUtils.ConvertValue<string>(reader["MobilePhone"]);
			this._State = DataUtils.ConvertValue<int>(reader["State"]);
			this._Hours = DataUtils.ConvertValue<int>(reader["Hours"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
			this._Evaluate = DataUtils.ConvertValue<string>(reader["Evaluate"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._ID = DataUtils.ConvertValue<Guid>(row["ID"]);
			this._OrderTitle = DataUtils.ConvertValue<string>(row["OrderTitle"]);
			this._OrderDate = DataUtils.ConvertValue<string>(row["OrderDate"]);
			this._TrainPlaceId = DataUtils.ConvertValue<Guid?>(row["TrainPlaceId"]);
			this._TrainPlaceAddress = DataUtils.ConvertValue<string>(row["TrainPlaceAddress"]);
			this._TrainPlaceName = DataUtils.ConvertValue<string>(row["TrainPlaceName"]);
			this._CarId = DataUtils.ConvertValue<Guid?>(row["CarId"]);
			this._BrandModel = DataUtils.ConvertValue<string>(row["BrandModel"]);
			this._CarType = DataUtils.ConvertValue<string>(row["CarType"]);
			this._PlateNumber = DataUtils.ConvertValue<string>(row["PlateNumber"]);
			this._StudentId = DataUtils.ConvertValue<Guid>(row["StudentId"]);
			this._CourseId = DataUtils.ConvertValue<Guid?>(row["CourseId"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._RealName = DataUtils.ConvertValue<string>(row["RealName"]);
			this._MobilePhone = DataUtils.ConvertValue<string>(row["MobilePhone"]);
			this._State = DataUtils.ConvertValue<int>(row["State"]);
			this._Hours = DataUtils.ConvertValue<int>(row["Hours"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
			this._Evaluate = DataUtils.ConvertValue<string>(row["Evaluate"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Biz_CTCourseOrder");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Biz_CTCourseOrder","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderTitle = new Field("OrderTitle","Biz_CTCourseOrder","OrderTitle");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderDate = new Field("OrderDate","Biz_CTCourseOrder","OrderDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TrainPlaceId = new Field("TrainPlaceId","Biz_CTCourseOrder","TrainPlaceId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TrainPlaceAddress = new Field("TrainPlaceAddress","Biz_CTCourseOrder","TrainPlaceAddress");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TrainPlaceName = new Field("TrainPlaceName","Biz_CTCourseOrder","TrainPlaceName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CarId = new Field("CarId","Biz_CTCourseOrder","CarId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BrandModel = new Field("BrandModel","Biz_CTCourseOrder","BrandModel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CarType = new Field("CarType","Biz_CTCourseOrder","CarType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PlateNumber = new Field("PlateNumber","Biz_CTCourseOrder","PlateNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StudentId = new Field("StudentId","Biz_CTCourseOrder","StudentId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CourseId = new Field("CourseId","Biz_CTCourseOrder","CourseId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Biz_CTCourseOrder","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RealName = new Field("RealName","Biz_CTCourseOrder","RealName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MobilePhone = new Field("MobilePhone","Biz_CTCourseOrder","MobilePhone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","Biz_CTCourseOrder","State");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Hours = new Field("Hours","Biz_CTCourseOrder","Hours");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Biz_CTCourseOrder","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Evaluate = new Field("Evaluate","Biz_CTCourseOrder","Evaluate");
		}
		#endregion


	}
}

