//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//     Support: http://www.cnblogs.com/huxj
//     Website: http://www.ITdos.com/
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

	/// <summary>
	/// 实体类Biz_CTStudent 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class Biz_CTStudent : Entity 
	{
		public Biz_CTStudent():base("Biz_CTStudent") {}

		#region Model
		private Guid _ID;
		private string _NickName;
		private string _RealName;
		private string _MobilePhone;
		private string _StuWeChat;
		private Guid? _CoachId;
		private string _HeadImg;
		private string _Subject;
		private string _SubjectValue;
		private string _Subject2Evaluate;
		private string _Subject3Evaluate;
		private string _Province;
		private string _City;
		private string _Address;
		private string _School;
		private string _IDNumber;
		private string _CarType;
		private string _StuFrom;
		private string _CoachType;
		private string _ApplyFor;
		private string _ApplyPlace;
		private DateTime _CreateTime;
		private string _Remark;
		private string _Subject2ProEvaluate;
		private string _Subject3ProEvaluate;
		private int _Sex;
		/// <summary>
		/// 
		/// </summary>
		public Guid ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NickName
		{
			get{ return _NickName; }
			set
			{
				this.OnPropertyValueChange(_.NickName,_NickName,value);
				this._NickName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RealName
		{
			get{ return _RealName; }
			set
			{
				this.OnPropertyValueChange(_.RealName,_RealName,value);
				this._RealName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MobilePhone
		{
			get{ return _MobilePhone; }
			set
			{
				this.OnPropertyValueChange(_.MobilePhone,_MobilePhone,value);
				this._MobilePhone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StuWeChat
		{
			get{ return _StuWeChat; }
			set
			{
				this.OnPropertyValueChange(_.StuWeChat,_StuWeChat,value);
				this._StuWeChat=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CoachId
		{
			get{ return _CoachId; }
			set
			{
				this.OnPropertyValueChange(_.CoachId,_CoachId,value);
				this._CoachId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HeadImg
		{
			get{ return _HeadImg; }
			set
			{
				this.OnPropertyValueChange(_.HeadImg,_HeadImg,value);
				this._HeadImg=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject
		{
			get{ return _Subject; }
			set
			{
				this.OnPropertyValueChange(_.Subject,_Subject,value);
				this._Subject=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SubjectValue
		{
			get{ return _SubjectValue; }
			set
			{
				this.OnPropertyValueChange(_.SubjectValue,_SubjectValue,value);
				this._SubjectValue=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject2Evaluate
		{
			get{ return _Subject2Evaluate; }
			set
			{
				this.OnPropertyValueChange(_.Subject2Evaluate,_Subject2Evaluate,value);
				this._Subject2Evaluate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject3Evaluate
		{
			get{ return _Subject3Evaluate; }
			set
			{
				this.OnPropertyValueChange(_.Subject3Evaluate,_Subject3Evaluate,value);
				this._Subject3Evaluate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Province
		{
			get{ return _Province; }
			set
			{
				this.OnPropertyValueChange(_.Province,_Province,value);
				this._Province=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string City
		{
			get{ return _City; }
			set
			{
				this.OnPropertyValueChange(_.City,_City,value);
				this._City=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string School
		{
			get{ return _School; }
			set
			{
				this.OnPropertyValueChange(_.School,_School,value);
				this._School=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IDNumber
		{
			get{ return _IDNumber; }
			set
			{
				this.OnPropertyValueChange(_.IDNumber,_IDNumber,value);
				this._IDNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CarType
		{
			get{ return _CarType; }
			set
			{
				this.OnPropertyValueChange(_.CarType,_CarType,value);
				this._CarType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StuFrom
		{
			get{ return _StuFrom; }
			set
			{
				this.OnPropertyValueChange(_.StuFrom,_StuFrom,value);
				this._StuFrom=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CoachType
		{
			get{ return _CoachType; }
			set
			{
				this.OnPropertyValueChange(_.CoachType,_CoachType,value);
				this._CoachType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ApplyFor
		{
			get{ return _ApplyFor; }
			set
			{
				this.OnPropertyValueChange(_.ApplyFor,_ApplyFor,value);
				this._ApplyFor=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ApplyPlace
		{
			get{ return _ApplyPlace; }
			set
			{
				this.OnPropertyValueChange(_.ApplyPlace,_ApplyPlace,value);
				this._ApplyPlace=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject2ProEvaluate
		{
			get{ return _Subject2ProEvaluate; }
			set
			{
				this.OnPropertyValueChange(_.Subject2ProEvaluate,_Subject2ProEvaluate,value);
				this._Subject2ProEvaluate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Subject3ProEvaluate
		{
			get{ return _Subject3ProEvaluate; }
			set
			{
				this.OnPropertyValueChange(_.Subject3ProEvaluate,_Subject3ProEvaluate,value);
				this._Subject3ProEvaluate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.NickName,
				_.RealName,
				_.MobilePhone,
				_.StuWeChat,
				_.CoachId,
				_.HeadImg,
				_.Subject,
				_.SubjectValue,
				_.Subject2Evaluate,
				_.Subject3Evaluate,
				_.Province,
				_.City,
				_.Address,
				_.School,
				_.IDNumber,
				_.CarType,
				_.StuFrom,
				_.CoachType,
				_.ApplyFor,
				_.ApplyPlace,
				_.CreateTime,
				_.Remark,
				_.Subject2ProEvaluate,
				_.Subject3ProEvaluate,
				_.Sex};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._NickName,
				this._RealName,
				this._MobilePhone,
				this._StuWeChat,
				this._CoachId,
				this._HeadImg,
				this._Subject,
				this._SubjectValue,
				this._Subject2Evaluate,
				this._Subject3Evaluate,
				this._Province,
				this._City,
				this._Address,
				this._School,
				this._IDNumber,
				this._CarType,
				this._StuFrom,
				this._CoachType,
				this._ApplyFor,
				this._ApplyPlace,
				this._CreateTime,
				this._Remark,
				this._Subject2ProEvaluate,
				this._Subject3ProEvaluate,
				this._Sex};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._ID = DataUtils.ConvertValue<Guid>(reader["ID"]);
			this._NickName = DataUtils.ConvertValue<string>(reader["NickName"]);
			this._RealName = DataUtils.ConvertValue<string>(reader["RealName"]);
			this._MobilePhone = DataUtils.ConvertValue<string>(reader["MobilePhone"]);
			this._StuWeChat = DataUtils.ConvertValue<string>(reader["StuWeChat"]);
			this._CoachId = DataUtils.ConvertValue<Guid?>(reader["CoachId"]);
			this._HeadImg = DataUtils.ConvertValue<string>(reader["HeadImg"]);
			this._Subject = DataUtils.ConvertValue<string>(reader["Subject"]);
			this._SubjectValue = DataUtils.ConvertValue<string>(reader["SubjectValue"]);
			this._Subject2Evaluate = DataUtils.ConvertValue<string>(reader["Subject2Evaluate"]);
			this._Subject3Evaluate = DataUtils.ConvertValue<string>(reader["Subject3Evaluate"]);
			this._Province = DataUtils.ConvertValue<string>(reader["Province"]);
			this._City = DataUtils.ConvertValue<string>(reader["City"]);
			this._Address = DataUtils.ConvertValue<string>(reader["Address"]);
			this._School = DataUtils.ConvertValue<string>(reader["School"]);
			this._IDNumber = DataUtils.ConvertValue<string>(reader["IDNumber"]);
			this._CarType = DataUtils.ConvertValue<string>(reader["CarType"]);
			this._StuFrom = DataUtils.ConvertValue<string>(reader["StuFrom"]);
			this._CoachType = DataUtils.ConvertValue<string>(reader["CoachType"]);
			this._ApplyFor = DataUtils.ConvertValue<string>(reader["ApplyFor"]);
			this._ApplyPlace = DataUtils.ConvertValue<string>(reader["ApplyPlace"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
			this._Subject2ProEvaluate = DataUtils.ConvertValue<string>(reader["Subject2ProEvaluate"]);
			this._Subject3ProEvaluate = DataUtils.ConvertValue<string>(reader["Subject3ProEvaluate"]);
			this._Sex = DataUtils.ConvertValue<int>(reader["Sex"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._ID = DataUtils.ConvertValue<Guid>(row["ID"]);
			this._NickName = DataUtils.ConvertValue<string>(row["NickName"]);
			this._RealName = DataUtils.ConvertValue<string>(row["RealName"]);
			this._MobilePhone = DataUtils.ConvertValue<string>(row["MobilePhone"]);
			this._StuWeChat = DataUtils.ConvertValue<string>(row["StuWeChat"]);
			this._CoachId = DataUtils.ConvertValue<Guid?>(row["CoachId"]);
			this._HeadImg = DataUtils.ConvertValue<string>(row["HeadImg"]);
			this._Subject = DataUtils.ConvertValue<string>(row["Subject"]);
			this._SubjectValue = DataUtils.ConvertValue<string>(row["SubjectValue"]);
			this._Subject2Evaluate = DataUtils.ConvertValue<string>(row["Subject2Evaluate"]);
			this._Subject3Evaluate = DataUtils.ConvertValue<string>(row["Subject3Evaluate"]);
			this._Province = DataUtils.ConvertValue<string>(row["Province"]);
			this._City = DataUtils.ConvertValue<string>(row["City"]);
			this._Address = DataUtils.ConvertValue<string>(row["Address"]);
			this._School = DataUtils.ConvertValue<string>(row["School"]);
			this._IDNumber = DataUtils.ConvertValue<string>(row["IDNumber"]);
			this._CarType = DataUtils.ConvertValue<string>(row["CarType"]);
			this._StuFrom = DataUtils.ConvertValue<string>(row["StuFrom"]);
			this._CoachType = DataUtils.ConvertValue<string>(row["CoachType"]);
			this._ApplyFor = DataUtils.ConvertValue<string>(row["ApplyFor"]);
			this._ApplyPlace = DataUtils.ConvertValue<string>(row["ApplyPlace"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
			this._Subject2ProEvaluate = DataUtils.ConvertValue<string>(row["Subject2ProEvaluate"]);
			this._Subject3ProEvaluate = DataUtils.ConvertValue<string>(row["Subject3ProEvaluate"]);
			this._Sex = DataUtils.ConvertValue<int>(row["Sex"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Biz_CTStudent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Biz_CTStudent","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NickName = new Field("NickName","Biz_CTStudent","NickName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RealName = new Field("RealName","Biz_CTStudent","RealName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MobilePhone = new Field("MobilePhone","Biz_CTStudent","MobilePhone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuWeChat = new Field("StuWeChat","Biz_CTStudent","StuWeChat");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CoachId = new Field("CoachId","Biz_CTStudent","CoachId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HeadImg = new Field("HeadImg","Biz_CTStudent","HeadImg");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject = new Field("Subject","Biz_CTStudent","Subject");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjectValue = new Field("SubjectValue","Biz_CTStudent","SubjectValue");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject2Evaluate = new Field("Subject2Evaluate","Biz_CTStudent","Subject2Evaluate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject3Evaluate = new Field("Subject3Evaluate","Biz_CTStudent","Subject3Evaluate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Province = new Field("Province","Biz_CTStudent","Province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City","Biz_CTStudent","City");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address","Biz_CTStudent","Address");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field School = new Field("School","Biz_CTStudent","School");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IDNumber = new Field("IDNumber","Biz_CTStudent","IDNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CarType = new Field("CarType","Biz_CTStudent","CarType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuFrom = new Field("StuFrom","Biz_CTStudent","StuFrom");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CoachType = new Field("CoachType","Biz_CTStudent","CoachType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApplyFor = new Field("ApplyFor","Biz_CTStudent","ApplyFor");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApplyPlace = new Field("ApplyPlace","Biz_CTStudent","ApplyPlace");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Biz_CTStudent","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Biz_CTStudent","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject2ProEvaluate = new Field("Subject2ProEvaluate","Biz_CTStudent","Subject2ProEvaluate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Subject3ProEvaluate = new Field("Subject3ProEvaluate","Biz_CTStudent","Subject3ProEvaluate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","Biz_CTStudent","Sex");
		}
		#endregion


	}
}

