//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Support: http://www.cnblogs.com/huxj
//     Website: http://www.ITdos.com/
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

    /// <summary>
    /// 实体类Biz_AnalogExam 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public partial class Biz_AnalogExam : Entity
    {
        public Biz_AnalogExam() : base("Biz_AnalogExam") { }

        #region Model
        private Guid _ID;
        private Guid? _BatchID;
        private string _SerialNumber;
        private string _Number;
        private int? _SortNumber;
        private string _Subject;
        private string _SubjectValue;
        private string _DrivingType;
        private Guid? _PlanChildId;
        private Guid? _CarId;
        private string _CarNumber;
        private Guid? _OldCarId;
        private string _OldCarNumber;
        private Guid? _CostId;
        private string _ExamTime;
        private string _ExamTimeSpan;
        private string _IDNumberTwo;
        private string _IDNumber;
        private string _Name;
        private string _NameTwo;
        private string _WeChat;
        private string _Phone;
        private string _MobilePhoneTwo;
        private string _MobilePhone;
        private Guid? _OperatorId;
        private string _Operator;
        private DateTime? _PayTime;
        private string _PayType;
        private string _OperatorType;
        private Guid? _HelperId;
        private string _Helper;
        private string _OldHelper;
        private Guid? _OldHelperId;
        private Guid _ExamRoomId;
        private bool _IsSure;
        private DateTime? _SureTime;
        private string _SureHelper;
        private decimal _Cost;
        private decimal? _RealCost;
        private decimal? _Discount;
        private DateTime _CreateTime;
        private string _ExamName;
        private int _State;
        private Guid? _PayCoachOperatorId;
        private string _PayCoachOperator;
        private DateTime? _PayCoachTime;
        private bool _IsPayCoach;
        private string _IP;
        private bool _IsPayHelper;
        private DateTime? _PayHelperTime;
        private string _PayHelperOperator;
        private Guid? _PayHelperOperatorId;
        private DateTime? _RefundTime;
        private decimal? _RefundCost;
        private int? _CallState;
        private DateTime? _GetOnTime;
        private DateTime? _SignInTime;
        private DateTime? _PrintTime;
        private int _PrintCount;
        private string _AddPrintOpertor;
        private Guid? _AddPrintOpertorId;
        private DateTime? _AddPrintOpertorTime;
        private string _CoachName;
        private Guid? _CoachId;
        private string _SchoolName;
        private Guid? _SchoolId;
        private bool _IsWeChartSure;
        private DateTime? _WeChartSureTime;
        private decimal _CoachPMoney;
        private decimal _HelperPMoney;
        private decimal _OCoachPMoney;
        private decimal _CarPMoney;
        private DateTime? _CallTime;
        private DateTime? _IceFrozenTime;
        private string _AutoRemark;
        private DateTime? _GetOffTime;
        private string _NewSerialNumber;
        private DateTime? _RefundPrintTime;
        private Guid? _RefundPrintOpertorId;
        private string _RefundPrintOpertor;
        private int _RefundPrintCount;
        private string _RefundOpertor;
        private Guid? _RefundOpertorId;
        private Guid? _RefundId;
        private decimal _Fee;
        private DateTime? _CancelTime;
        private bool _IsPutTop;
        private DateTime? _PutTopTime;
        private string _PutTopOpertor;
        private Guid? _PutTopOpertorId;
        private Guid? _PaySchoolId;
        private string _PaySchool;
        private DateTime? _CarChangeTime;
        private DateTime? _ExpireRepairTime;
        private string _ExpireRepairOpertor;
        private Guid? _ExpireRepairOpertorId;
        private bool _IsOverdue;
        private string _OrderFrom;
        private bool _IsEvaluate;
        /// <summary>
        /// 
        /// </summary>
        public Guid ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange(_.ID, _ID, value);
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? BatchID
        {
            get { return _BatchID; }
            set
            {
                this.OnPropertyValueChange(_.BatchID, _BatchID, value);
                this._BatchID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SerialNumber
        {
            get { return _SerialNumber; }
            set
            {
                this.OnPropertyValueChange(_.SerialNumber, _SerialNumber, value);
                this._SerialNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Number
        {
            get { return _Number; }
            set
            {
                this.OnPropertyValueChange(_.Number, _Number, value);
                this._Number = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? SortNumber
        {
            get { return _SortNumber; }
            set
            {
                this.OnPropertyValueChange(_.SortNumber, _SortNumber, value);
                this._SortNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Subject
        {
            get { return _Subject; }
            set
            {
                this.OnPropertyValueChange(_.Subject, _Subject, value);
                this._Subject = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SubjectValue
        {
            get { return _SubjectValue; }
            set
            {
                this.OnPropertyValueChange(_.SubjectValue, _SubjectValue, value);
                this._SubjectValue = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DrivingType
        {
            get { return _DrivingType; }
            set
            {
                this.OnPropertyValueChange(_.DrivingType, _DrivingType, value);
                this._DrivingType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? PlanChildId
        {
            get { return _PlanChildId; }
            set
            {
                this.OnPropertyValueChange(_.PlanChildId, _PlanChildId, value);
                this._PlanChildId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? CarId
        {
            get { return _CarId; }
            set
            {
                this.OnPropertyValueChange(_.CarId, _CarId, value);
                this._CarId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CarNumber
        {
            get { return _CarNumber; }
            set
            {
                this.OnPropertyValueChange(_.CarNumber, _CarNumber, value);
                this._CarNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? OldCarId
        {
            get { return _OldCarId; }
            set
            {
                this.OnPropertyValueChange(_.OldCarId, _OldCarId, value);
                this._OldCarId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OldCarNumber
        {
            get { return _OldCarNumber; }
            set
            {
                this.OnPropertyValueChange(_.OldCarNumber, _OldCarNumber, value);
                this._OldCarNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? CostId
        {
            get { return _CostId; }
            set
            {
                this.OnPropertyValueChange(_.CostId, _CostId, value);
                this._CostId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExamTime
        {
            get { return _ExamTime; }
            set
            {
                this.OnPropertyValueChange(_.ExamTime, _ExamTime, value);
                this._ExamTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExamTimeSpan
        {
            get { return _ExamTimeSpan; }
            set
            {
                this.OnPropertyValueChange(_.ExamTimeSpan, _ExamTimeSpan, value);
                this._ExamTimeSpan = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IDNumberTwo
        {
            get { return _IDNumberTwo; }
            set
            {
                this.OnPropertyValueChange(_.IDNumberTwo, _IDNumberTwo, value);
                this._IDNumberTwo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IDNumber
        {
            get { return _IDNumber; }
            set
            {
                this.OnPropertyValueChange(_.IDNumber, _IDNumber, value);
                this._IDNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange(_.Name, _Name, value);
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NameTwo
        {
            get { return _NameTwo; }
            set
            {
                this.OnPropertyValueChange(_.NameTwo, _NameTwo, value);
                this._NameTwo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string WeChat
        {
            get { return _WeChat; }
            set
            {
                this.OnPropertyValueChange(_.WeChat, _WeChat, value);
                this._WeChat = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Phone
        {
            get { return _Phone; }
            set
            {
                this.OnPropertyValueChange(_.Phone, _Phone, value);
                this._Phone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhoneTwo
        {
            get { return _MobilePhoneTwo; }
            set
            {
                this.OnPropertyValueChange(_.MobilePhoneTwo, _MobilePhoneTwo, value);
                this._MobilePhoneTwo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone
        {
            get { return _MobilePhone; }
            set
            {
                this.OnPropertyValueChange(_.MobilePhone, _MobilePhone, value);
                this._MobilePhone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? OperatorId
        {
            get { return _OperatorId; }
            set
            {
                this.OnPropertyValueChange(_.OperatorId, _OperatorId, value);
                this._OperatorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Operator
        {
            get { return _Operator; }
            set
            {
                this.OnPropertyValueChange(_.Operator, _Operator, value);
                this._Operator = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? PayTime
        {
            get { return _PayTime; }
            set
            {
                this.OnPropertyValueChange(_.PayTime, _PayTime, value);
                this._PayTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PayType
        {
            get { return _PayType; }
            set
            {
                this.OnPropertyValueChange(_.PayType, _PayType, value);
                this._PayType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OperatorType
        {
            get { return _OperatorType; }
            set
            {
                this.OnPropertyValueChange(_.OperatorType, _OperatorType, value);
                this._OperatorType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? HelperId
        {
            get { return _HelperId; }
            set
            {
                this.OnPropertyValueChange(_.HelperId, _HelperId, value);
                this._HelperId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Helper
        {
            get { return _Helper; }
            set
            {
                this.OnPropertyValueChange(_.Helper, _Helper, value);
                this._Helper = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OldHelper
        {
            get { return _OldHelper; }
            set
            {
                this.OnPropertyValueChange(_.OldHelper, _OldHelper, value);
                this._OldHelper = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? OldHelperId
        {
            get { return _OldHelperId; }
            set
            {
                this.OnPropertyValueChange(_.OldHelperId, _OldHelperId, value);
                this._OldHelperId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid ExamRoomId
        {
            get { return _ExamRoomId; }
            set
            {
                this.OnPropertyValueChange(_.ExamRoomId, _ExamRoomId, value);
                this._ExamRoomId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsSure
        {
            get { return _IsSure; }
            set
            {
                this.OnPropertyValueChange(_.IsSure, _IsSure, value);
                this._IsSure = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? SureTime
        {
            get { return _SureTime; }
            set
            {
                this.OnPropertyValueChange(_.SureTime, _SureTime, value);
                this._SureTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SureHelper
        {
            get { return _SureHelper; }
            set
            {
                this.OnPropertyValueChange(_.SureHelper, _SureHelper, value);
                this._SureHelper = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal Cost
        {
            get { return _Cost; }
            set
            {
                this.OnPropertyValueChange(_.Cost, _Cost, value);
                this._Cost = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? RealCost
        {
            get { return _RealCost; }
            set
            {
                this.OnPropertyValueChange(_.RealCost, _RealCost, value);
                this._RealCost = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Discount
        {
            get { return _Discount; }
            set
            {
                this.OnPropertyValueChange(_.Discount, _Discount, value);
                this._Discount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange(_.CreateTime, _CreateTime, value);
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExamName
        {
            get { return _ExamName; }
            set
            {
                this.OnPropertyValueChange(_.ExamName, _ExamName, value);
                this._ExamName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int State
        {
            get { return _State; }
            set
            {
                this.OnPropertyValueChange(_.State, _State, value);
                this._State = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? PayCoachOperatorId
        {
            get { return _PayCoachOperatorId; }
            set
            {
                this.OnPropertyValueChange(_.PayCoachOperatorId, _PayCoachOperatorId, value);
                this._PayCoachOperatorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PayCoachOperator
        {
            get { return _PayCoachOperator; }
            set
            {
                this.OnPropertyValueChange(_.PayCoachOperator, _PayCoachOperator, value);
                this._PayCoachOperator = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? PayCoachTime
        {
            get { return _PayCoachTime; }
            set
            {
                this.OnPropertyValueChange(_.PayCoachTime, _PayCoachTime, value);
                this._PayCoachTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsPayCoach
        {
            get { return _IsPayCoach; }
            set
            {
                this.OnPropertyValueChange(_.IsPayCoach, _IsPayCoach, value);
                this._IsPayCoach = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IP
        {
            get { return _IP; }
            set
            {
                this.OnPropertyValueChange(_.IP, _IP, value);
                this._IP = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsPayHelper
        {
            get { return _IsPayHelper; }
            set
            {
                this.OnPropertyValueChange(_.IsPayHelper, _IsPayHelper, value);
                this._IsPayHelper = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? PayHelperTime
        {
            get { return _PayHelperTime; }
            set
            {
                this.OnPropertyValueChange(_.PayHelperTime, _PayHelperTime, value);
                this._PayHelperTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PayHelperOperator
        {
            get { return _PayHelperOperator; }
            set
            {
                this.OnPropertyValueChange(_.PayHelperOperator, _PayHelperOperator, value);
                this._PayHelperOperator = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? PayHelperOperatorId
        {
            get { return _PayHelperOperatorId; }
            set
            {
                this.OnPropertyValueChange(_.PayHelperOperatorId, _PayHelperOperatorId, value);
                this._PayHelperOperatorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? RefundTime
        {
            get { return _RefundTime; }
            set
            {
                this.OnPropertyValueChange(_.RefundTime, _RefundTime, value);
                this._RefundTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? RefundCost
        {
            get { return _RefundCost; }
            set
            {
                this.OnPropertyValueChange(_.RefundCost, _RefundCost, value);
                this._RefundCost = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CallState
        {
            get { return _CallState; }
            set
            {
                this.OnPropertyValueChange(_.CallState, _CallState, value);
                this._CallState = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? GetOnTime
        {
            get { return _GetOnTime; }
            set
            {
                this.OnPropertyValueChange(_.GetOnTime, _GetOnTime, value);
                this._GetOnTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? SignInTime
        {
            get { return _SignInTime; }
            set
            {
                this.OnPropertyValueChange(_.SignInTime, _SignInTime, value);
                this._SignInTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? PrintTime
        {
            get { return _PrintTime; }
            set
            {
                this.OnPropertyValueChange(_.PrintTime, _PrintTime, value);
                this._PrintTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int PrintCount
        {
            get { return _PrintCount; }
            set
            {
                this.OnPropertyValueChange(_.PrintCount, _PrintCount, value);
                this._PrintCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string AddPrintOpertor
        {
            get { return _AddPrintOpertor; }
            set
            {
                this.OnPropertyValueChange(_.AddPrintOpertor, _AddPrintOpertor, value);
                this._AddPrintOpertor = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? AddPrintOpertorId
        {
            get { return _AddPrintOpertorId; }
            set
            {
                this.OnPropertyValueChange(_.AddPrintOpertorId, _AddPrintOpertorId, value);
                this._AddPrintOpertorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? AddPrintOpertorTime
        {
            get { return _AddPrintOpertorTime; }
            set
            {
                this.OnPropertyValueChange(_.AddPrintOpertorTime, _AddPrintOpertorTime, value);
                this._AddPrintOpertorTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CoachName
        {
            get { return _CoachName; }
            set
            {
                this.OnPropertyValueChange(_.CoachName, _CoachName, value);
                this._CoachName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? CoachId
        {
            get { return _CoachId; }
            set
            {
                this.OnPropertyValueChange(_.CoachId, _CoachId, value);
                this._CoachId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SchoolName
        {
            get { return _SchoolName; }
            set
            {
                this.OnPropertyValueChange(_.SchoolName, _SchoolName, value);
                this._SchoolName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? SchoolId
        {
            get { return _SchoolId; }
            set
            {
                this.OnPropertyValueChange(_.SchoolId, _SchoolId, value);
                this._SchoolId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsWeChartSure
        {
            get { return _IsWeChartSure; }
            set
            {
                this.OnPropertyValueChange(_.IsWeChartSure, _IsWeChartSure, value);
                this._IsWeChartSure = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? WeChartSureTime
        {
            get { return _WeChartSureTime; }
            set
            {
                this.OnPropertyValueChange(_.WeChartSureTime, _WeChartSureTime, value);
                this._WeChartSureTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal CoachPMoney
        {
            get { return _CoachPMoney; }
            set
            {
                this.OnPropertyValueChange(_.CoachPMoney, _CoachPMoney, value);
                this._CoachPMoney = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal HelperPMoney
        {
            get { return _HelperPMoney; }
            set
            {
                this.OnPropertyValueChange(_.HelperPMoney, _HelperPMoney, value);
                this._HelperPMoney = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal OCoachPMoney
        {
            get { return _OCoachPMoney; }
            set
            {
                this.OnPropertyValueChange(_.OCoachPMoney, _OCoachPMoney, value);
                this._OCoachPMoney = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal CarPMoney
        {
            get { return _CarPMoney; }
            set
            {
                this.OnPropertyValueChange(_.CarPMoney, _CarPMoney, value);
                this._CarPMoney = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CallTime
        {
            get { return _CallTime; }
            set
            {
                this.OnPropertyValueChange(_.CallTime, _CallTime, value);
                this._CallTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? IceFrozenTime
        {
            get { return _IceFrozenTime; }
            set
            {
                this.OnPropertyValueChange(_.IceFrozenTime, _IceFrozenTime, value);
                this._IceFrozenTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string AutoRemark
        {
            get { return _AutoRemark; }
            set
            {
                this.OnPropertyValueChange(_.AutoRemark, _AutoRemark, value);
                this._AutoRemark = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? GetOffTime
        {
            get { return _GetOffTime; }
            set
            {
                this.OnPropertyValueChange(_.GetOffTime, _GetOffTime, value);
                this._GetOffTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NewSerialNumber
        {
            get { return _NewSerialNumber; }
            set
            {
                this.OnPropertyValueChange(_.NewSerialNumber, _NewSerialNumber, value);
                this._NewSerialNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? RefundPrintTime
        {
            get { return _RefundPrintTime; }
            set
            {
                this.OnPropertyValueChange(_.RefundPrintTime, _RefundPrintTime, value);
                this._RefundPrintTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? RefundPrintOpertorId
        {
            get { return _RefundPrintOpertorId; }
            set
            {
                this.OnPropertyValueChange(_.RefundPrintOpertorId, _RefundPrintOpertorId, value);
                this._RefundPrintOpertorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string RefundPrintOpertor
        {
            get { return _RefundPrintOpertor; }
            set
            {
                this.OnPropertyValueChange(_.RefundPrintOpertor, _RefundPrintOpertor, value);
                this._RefundPrintOpertor = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int RefundPrintCount
        {
            get { return _RefundPrintCount; }
            set
            {
                this.OnPropertyValueChange(_.RefundPrintCount, _RefundPrintCount, value);
                this._RefundPrintCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string RefundOpertor
        {
            get { return _RefundOpertor; }
            set
            {
                this.OnPropertyValueChange(_.RefundOpertor, _RefundOpertor, value);
                this._RefundOpertor = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? RefundOpertorId
        {
            get { return _RefundOpertorId; }
            set
            {
                this.OnPropertyValueChange(_.RefundOpertorId, _RefundOpertorId, value);
                this._RefundOpertorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? RefundId
        {
            get { return _RefundId; }
            set
            {
                this.OnPropertyValueChange(_.RefundId, _RefundId, value);
                this._RefundId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal Fee
        {
            get { return _Fee; }
            set
            {
                this.OnPropertyValueChange(_.Fee, _Fee, value);
                this._Fee = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CancelTime
        {
            get { return _CancelTime; }
            set
            {
                this.OnPropertyValueChange(_.CancelTime, _CancelTime, value);
                this._CancelTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsPutTop
        {
            get { return _IsPutTop; }
            set
            {
                this.OnPropertyValueChange(_.IsPutTop, _IsPutTop, value);
                this._IsPutTop = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? PutTopTime
        {
            get { return _PutTopTime; }
            set
            {
                this.OnPropertyValueChange(_.PutTopTime, _PutTopTime, value);
                this._PutTopTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PutTopOpertor
        {
            get { return _PutTopOpertor; }
            set
            {
                this.OnPropertyValueChange(_.PutTopOpertor, _PutTopOpertor, value);
                this._PutTopOpertor = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? PutTopOpertorId
        {
            get { return _PutTopOpertorId; }
            set
            {
                this.OnPropertyValueChange(_.PutTopOpertorId, _PutTopOpertorId, value);
                this._PutTopOpertorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? PaySchoolId
        {
            get { return _PaySchoolId; }
            set
            {
                this.OnPropertyValueChange(_.PaySchoolId, _PaySchoolId, value);
                this._PaySchoolId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PaySchool
        {
            get { return _PaySchool; }
            set
            {
                this.OnPropertyValueChange(_.PaySchool, _PaySchool, value);
                this._PaySchool = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CarChangeTime
        {
            get { return _CarChangeTime; }
            set
            {
                this.OnPropertyValueChange(_.CarChangeTime, _CarChangeTime, value);
                this._CarChangeTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? ExpireRepairTime
        {
            get { return _ExpireRepairTime; }
            set
            {
                this.OnPropertyValueChange(_.ExpireRepairTime, _ExpireRepairTime, value);
                this._ExpireRepairTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExpireRepairOpertor
        {
            get { return _ExpireRepairOpertor; }
            set
            {
                this.OnPropertyValueChange(_.ExpireRepairOpertor, _ExpireRepairOpertor, value);
                this._ExpireRepairOpertor = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? ExpireRepairOpertorId
        {
            get { return _ExpireRepairOpertorId; }
            set
            {
                this.OnPropertyValueChange(_.ExpireRepairOpertorId, _ExpireRepairOpertorId, value);
                this._ExpireRepairOpertorId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsOverdue
        {
            get { return _IsOverdue; }
            set
            {
                this.OnPropertyValueChange(_.IsOverdue, _IsOverdue, value);
                this._IsOverdue = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OrderFrom
        {
            get { return _OrderFrom; }
            set
            {
                this.OnPropertyValueChange(_.OrderFrom, _OrderFrom, value);
                this._OrderFrom = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool IsEvaluate
        {
            get { return _IsEvaluate; }
            set
            {
                this.OnPropertyValueChange(_.IsEvaluate, _IsEvaluate, value);
                this._IsEvaluate = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BatchID,
				_.SerialNumber,
				_.Number,
				_.SortNumber,
				_.Subject,
				_.SubjectValue,
				_.DrivingType,
				_.PlanChildId,
				_.CarId,
				_.CarNumber,
				_.OldCarId,
				_.OldCarNumber,
				_.CostId,
				_.ExamTime,
				_.ExamTimeSpan,
				_.IDNumberTwo,
				_.IDNumber,
				_.Name,
				_.NameTwo,
				_.WeChat,
				_.Phone,
				_.MobilePhoneTwo,
				_.MobilePhone,
				_.OperatorId,
				_.Operator,
				_.PayTime,
				_.PayType,
				_.OperatorType,
				_.HelperId,
				_.Helper,
				_.OldHelper,
				_.OldHelperId,
				_.ExamRoomId,
				_.IsSure,
				_.SureTime,
				_.SureHelper,
				_.Cost,
				_.RealCost,
				_.Discount,
				_.CreateTime,
				_.ExamName,
				_.State,
				_.PayCoachOperatorId,
				_.PayCoachOperator,
				_.PayCoachTime,
				_.IsPayCoach,
				_.IP,
				_.IsPayHelper,
				_.PayHelperTime,
				_.PayHelperOperator,
				_.PayHelperOperatorId,
				_.RefundTime,
				_.RefundCost,
				_.CallState,
				_.GetOnTime,
				_.SignInTime,
				_.PrintTime,
				_.PrintCount,
				_.AddPrintOpertor,
				_.AddPrintOpertorId,
				_.AddPrintOpertorTime,
				_.CoachName,
				_.CoachId,
				_.SchoolName,
				_.SchoolId,
				_.IsWeChartSure,
				_.WeChartSureTime,
				_.CoachPMoney,
				_.HelperPMoney,
				_.OCoachPMoney,
				_.CarPMoney,
				_.CallTime,
				_.IceFrozenTime,
				_.AutoRemark,
				_.GetOffTime,
				_.NewSerialNumber,
				_.RefundPrintTime,
				_.RefundPrintOpertorId,
				_.RefundPrintOpertor,
				_.RefundPrintCount,
				_.RefundOpertor,
				_.RefundOpertorId,
				_.RefundId,
				_.Fee,
				_.CancelTime,
				_.IsPutTop,
				_.PutTopTime,
				_.PutTopOpertor,
				_.PutTopOpertorId,
				_.PaySchoolId,
				_.PaySchool,
				_.CarChangeTime,
				_.ExpireRepairTime,
				_.ExpireRepairOpertor,
				_.ExpireRepairOpertorId,
				_.IsOverdue,
				_.OrderFrom,
				_.IsEvaluate};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BatchID,
				this._SerialNumber,
				this._Number,
				this._SortNumber,
				this._Subject,
				this._SubjectValue,
				this._DrivingType,
				this._PlanChildId,
				this._CarId,
				this._CarNumber,
				this._OldCarId,
				this._OldCarNumber,
				this._CostId,
				this._ExamTime,
				this._ExamTimeSpan,
				this._IDNumberTwo,
				this._IDNumber,
				this._Name,
				this._NameTwo,
				this._WeChat,
				this._Phone,
				this._MobilePhoneTwo,
				this._MobilePhone,
				this._OperatorId,
				this._Operator,
				this._PayTime,
				this._PayType,
				this._OperatorType,
				this._HelperId,
				this._Helper,
				this._OldHelper,
				this._OldHelperId,
				this._ExamRoomId,
				this._IsSure,
				this._SureTime,
				this._SureHelper,
				this._Cost,
				this._RealCost,
				this._Discount,
				this._CreateTime,
				this._ExamName,
				this._State,
				this._PayCoachOperatorId,
				this._PayCoachOperator,
				this._PayCoachTime,
				this._IsPayCoach,
				this._IP,
				this._IsPayHelper,
				this._PayHelperTime,
				this._PayHelperOperator,
				this._PayHelperOperatorId,
				this._RefundTime,
				this._RefundCost,
				this._CallState,
				this._GetOnTime,
				this._SignInTime,
				this._PrintTime,
				this._PrintCount,
				this._AddPrintOpertor,
				this._AddPrintOpertorId,
				this._AddPrintOpertorTime,
				this._CoachName,
				this._CoachId,
				this._SchoolName,
				this._SchoolId,
				this._IsWeChartSure,
				this._WeChartSureTime,
				this._CoachPMoney,
				this._HelperPMoney,
				this._OCoachPMoney,
				this._CarPMoney,
				this._CallTime,
				this._IceFrozenTime,
				this._AutoRemark,
				this._GetOffTime,
				this._NewSerialNumber,
				this._RefundPrintTime,
				this._RefundPrintOpertorId,
				this._RefundPrintOpertor,
				this._RefundPrintCount,
				this._RefundOpertor,
				this._RefundOpertorId,
				this._RefundId,
				this._Fee,
				this._CancelTime,
				this._IsPutTop,
				this._PutTopTime,
				this._PutTopOpertor,
				this._PutTopOpertorId,
				this._PaySchoolId,
				this._PaySchool,
				this._CarChangeTime,
				this._ExpireRepairTime,
				this._ExpireRepairOpertor,
				this._ExpireRepairOpertorId,
				this._IsOverdue,
				this._OrderFrom,
				this._IsEvaluate};
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(IDataReader reader)
        {
            this._ID = DataUtils.ConvertValue<Guid>(reader["ID"]);
            this._BatchID = DataUtils.ConvertValue<Guid?>(reader["BatchID"]);
            this._SerialNumber = DataUtils.ConvertValue<string>(reader["SerialNumber"]);
            this._Number = DataUtils.ConvertValue<string>(reader["Number"]);
            this._SortNumber = DataUtils.ConvertValue<int?>(reader["SortNumber"]);
            this._Subject = DataUtils.ConvertValue<string>(reader["Subject"]);
            this._SubjectValue = DataUtils.ConvertValue<string>(reader["SubjectValue"]);
            this._DrivingType = DataUtils.ConvertValue<string>(reader["DrivingType"]);
            this._PlanChildId = DataUtils.ConvertValue<Guid?>(reader["PlanChildId"]);
            this._CarId = DataUtils.ConvertValue<Guid?>(reader["CarId"]);
            this._CarNumber = DataUtils.ConvertValue<string>(reader["CarNumber"]);
            this._OldCarId = DataUtils.ConvertValue<Guid?>(reader["OldCarId"]);
            this._OldCarNumber = DataUtils.ConvertValue<string>(reader["OldCarNumber"]);
            this._CostId = DataUtils.ConvertValue<Guid?>(reader["CostId"]);
            this._ExamTime = DataUtils.ConvertValue<string>(reader["ExamTime"]);
            this._ExamTimeSpan = DataUtils.ConvertValue<string>(reader["ExamTimeSpan"]);
            this._IDNumberTwo = DataUtils.ConvertValue<string>(reader["IDNumberTwo"]);
            this._IDNumber = DataUtils.ConvertValue<string>(reader["IDNumber"]);
            this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
            this._NameTwo = DataUtils.ConvertValue<string>(reader["NameTwo"]);
            this._WeChat = DataUtils.ConvertValue<string>(reader["WeChat"]);
            this._Phone = DataUtils.ConvertValue<string>(reader["Phone"]);
            this._MobilePhoneTwo = DataUtils.ConvertValue<string>(reader["MobilePhoneTwo"]);
            this._MobilePhone = DataUtils.ConvertValue<string>(reader["MobilePhone"]);
            this._OperatorId = DataUtils.ConvertValue<Guid?>(reader["OperatorId"]);
            this._Operator = DataUtils.ConvertValue<string>(reader["Operator"]);
            this._PayTime = DataUtils.ConvertValue<DateTime?>(reader["PayTime"]);
            this._PayType = DataUtils.ConvertValue<string>(reader["PayType"]);
            this._OperatorType = DataUtils.ConvertValue<string>(reader["OperatorType"]);
            this._HelperId = DataUtils.ConvertValue<Guid?>(reader["HelperId"]);
            this._Helper = DataUtils.ConvertValue<string>(reader["Helper"]);
            this._OldHelper = DataUtils.ConvertValue<string>(reader["OldHelper"]);
            this._OldHelperId = DataUtils.ConvertValue<Guid?>(reader["OldHelperId"]);
            this._ExamRoomId = DataUtils.ConvertValue<Guid>(reader["ExamRoomId"]);
            this._IsSure = DataUtils.ConvertValue<bool>(reader["IsSure"]);
            this._SureTime = DataUtils.ConvertValue<DateTime?>(reader["SureTime"]);
            this._SureHelper = DataUtils.ConvertValue<string>(reader["SureHelper"]);
            this._Cost = DataUtils.ConvertValue<decimal>(reader["Cost"]);
            this._RealCost = DataUtils.ConvertValue<decimal?>(reader["RealCost"]);
            this._Discount = DataUtils.ConvertValue<decimal?>(reader["Discount"]);
            this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
            this._ExamName = DataUtils.ConvertValue<string>(reader["ExamName"]);
            this._State = DataUtils.ConvertValue<int>(reader["State"]);
            this._PayCoachOperatorId = DataUtils.ConvertValue<Guid?>(reader["PayCoachOperatorId"]);
            this._PayCoachOperator = DataUtils.ConvertValue<string>(reader["PayCoachOperator"]);
            this._PayCoachTime = DataUtils.ConvertValue<DateTime?>(reader["PayCoachTime"]);
            this._IsPayCoach = DataUtils.ConvertValue<bool>(reader["IsPayCoach"]);
            this._IP = DataUtils.ConvertValue<string>(reader["IP"]);
            this._IsPayHelper = DataUtils.ConvertValue<bool>(reader["IsPayHelper"]);
            this._PayHelperTime = DataUtils.ConvertValue<DateTime?>(reader["PayHelperTime"]);
            this._PayHelperOperator = DataUtils.ConvertValue<string>(reader["PayHelperOperator"]);
            this._PayHelperOperatorId = DataUtils.ConvertValue<Guid?>(reader["PayHelperOperatorId"]);
            this._RefundTime = DataUtils.ConvertValue<DateTime?>(reader["RefundTime"]);
            this._RefundCost = DataUtils.ConvertValue<decimal?>(reader["RefundCost"]);
            this._CallState = DataUtils.ConvertValue<int?>(reader["CallState"]);
            this._GetOnTime = DataUtils.ConvertValue<DateTime?>(reader["GetOnTime"]);
            this._SignInTime = DataUtils.ConvertValue<DateTime?>(reader["SignInTime"]);
            this._PrintTime = DataUtils.ConvertValue<DateTime?>(reader["PrintTime"]);
            this._PrintCount = DataUtils.ConvertValue<int>(reader["PrintCount"]);
            this._AddPrintOpertor = DataUtils.ConvertValue<string>(reader["AddPrintOpertor"]);
            this._AddPrintOpertorId = DataUtils.ConvertValue<Guid?>(reader["AddPrintOpertorId"]);
            this._AddPrintOpertorTime = DataUtils.ConvertValue<DateTime?>(reader["AddPrintOpertorTime"]);
            this._CoachName = DataUtils.ConvertValue<string>(reader["CoachName"]);
            this._CoachId = DataUtils.ConvertValue<Guid?>(reader["CoachId"]);
            this._SchoolName = DataUtils.ConvertValue<string>(reader["SchoolName"]);
            this._SchoolId = DataUtils.ConvertValue<Guid?>(reader["SchoolId"]);
            this._IsWeChartSure = DataUtils.ConvertValue<bool>(reader["IsWeChartSure"]);
            this._WeChartSureTime = DataUtils.ConvertValue<DateTime?>(reader["WeChartSureTime"]);
            this._CoachPMoney = DataUtils.ConvertValue<decimal>(reader["CoachPMoney"]);
            this._HelperPMoney = DataUtils.ConvertValue<decimal>(reader["HelperPMoney"]);
            this._OCoachPMoney = DataUtils.ConvertValue<decimal>(reader["OCoachPMoney"]);
            this._CarPMoney = DataUtils.ConvertValue<decimal>(reader["CarPMoney"]);
            this._CallTime = DataUtils.ConvertValue<DateTime?>(reader["CallTime"]);
            this._IceFrozenTime = DataUtils.ConvertValue<DateTime?>(reader["IceFrozenTime"]);
            this._AutoRemark = DataUtils.ConvertValue<string>(reader["AutoRemark"]);
            this._GetOffTime = DataUtils.ConvertValue<DateTime?>(reader["GetOffTime"]);
            this._NewSerialNumber = DataUtils.ConvertValue<string>(reader["NewSerialNumber"]);
            this._RefundPrintTime = DataUtils.ConvertValue<DateTime?>(reader["RefundPrintTime"]);
            this._RefundPrintOpertorId = DataUtils.ConvertValue<Guid?>(reader["RefundPrintOpertorId"]);
            this._RefundPrintOpertor = DataUtils.ConvertValue<string>(reader["RefundPrintOpertor"]);
            this._RefundPrintCount = DataUtils.ConvertValue<int>(reader["RefundPrintCount"]);
            this._RefundOpertor = DataUtils.ConvertValue<string>(reader["RefundOpertor"]);
            this._RefundOpertorId = DataUtils.ConvertValue<Guid?>(reader["RefundOpertorId"]);
            this._RefundId = DataUtils.ConvertValue<Guid?>(reader["RefundId"]);
            this._Fee = DataUtils.ConvertValue<decimal>(reader["Fee"]);
            this._CancelTime = DataUtils.ConvertValue<DateTime?>(reader["CancelTime"]);
            this._IsPutTop = DataUtils.ConvertValue<bool>(reader["IsPutTop"]);
            this._PutTopTime = DataUtils.ConvertValue<DateTime?>(reader["PutTopTime"]);
            this._PutTopOpertor = DataUtils.ConvertValue<string>(reader["PutTopOpertor"]);
            this._PutTopOpertorId = DataUtils.ConvertValue<Guid?>(reader["PutTopOpertorId"]);
            this._PaySchoolId = DataUtils.ConvertValue<Guid?>(reader["PaySchoolId"]);
            this._PaySchool = DataUtils.ConvertValue<string>(reader["PaySchool"]);
            this._CarChangeTime = DataUtils.ConvertValue<DateTime?>(reader["CarChangeTime"]);
            this._ExpireRepairTime = DataUtils.ConvertValue<DateTime?>(reader["ExpireRepairTime"]);
            this._ExpireRepairOpertor = DataUtils.ConvertValue<string>(reader["ExpireRepairOpertor"]);
            this._ExpireRepairOpertorId = DataUtils.ConvertValue<Guid?>(reader["ExpireRepairOpertorId"]);
            this._IsOverdue = DataUtils.ConvertValue<bool>(reader["IsOverdue"]);
            this._OrderFrom = DataUtils.ConvertValue<string>(reader["OrderFrom"]);
            this._IsEvaluate = DataUtils.ConvertValue<bool>(reader["IsEvaluate"]);
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(DataRow row)
        {
            this._ID = DataUtils.ConvertValue<Guid>(row["ID"]);
            this._BatchID = DataUtils.ConvertValue<Guid?>(row["BatchID"]);
            this._SerialNumber = DataUtils.ConvertValue<string>(row["SerialNumber"]);
            this._Number = DataUtils.ConvertValue<string>(row["Number"]);
            this._SortNumber = DataUtils.ConvertValue<int?>(row["SortNumber"]);
            this._Subject = DataUtils.ConvertValue<string>(row["Subject"]);
            this._SubjectValue = DataUtils.ConvertValue<string>(row["SubjectValue"]);
            this._DrivingType = DataUtils.ConvertValue<string>(row["DrivingType"]);
            this._PlanChildId = DataUtils.ConvertValue<Guid?>(row["PlanChildId"]);
            this._CarId = DataUtils.ConvertValue<Guid?>(row["CarId"]);
            this._CarNumber = DataUtils.ConvertValue<string>(row["CarNumber"]);
            this._OldCarId = DataUtils.ConvertValue<Guid?>(row["OldCarId"]);
            this._OldCarNumber = DataUtils.ConvertValue<string>(row["OldCarNumber"]);
            this._CostId = DataUtils.ConvertValue<Guid?>(row["CostId"]);
            this._ExamTime = DataUtils.ConvertValue<string>(row["ExamTime"]);
            this._ExamTimeSpan = DataUtils.ConvertValue<string>(row["ExamTimeSpan"]);
            this._IDNumberTwo = DataUtils.ConvertValue<string>(row["IDNumberTwo"]);
            this._IDNumber = DataUtils.ConvertValue<string>(row["IDNumber"]);
            this._Name = DataUtils.ConvertValue<string>(row["Name"]);
            this._NameTwo = DataUtils.ConvertValue<string>(row["NameTwo"]);
            this._WeChat = DataUtils.ConvertValue<string>(row["WeChat"]);
            this._Phone = DataUtils.ConvertValue<string>(row["Phone"]);
            this._MobilePhoneTwo = DataUtils.ConvertValue<string>(row["MobilePhoneTwo"]);
            this._MobilePhone = DataUtils.ConvertValue<string>(row["MobilePhone"]);
            this._OperatorId = DataUtils.ConvertValue<Guid?>(row["OperatorId"]);
            this._Operator = DataUtils.ConvertValue<string>(row["Operator"]);
            this._PayTime = DataUtils.ConvertValue<DateTime?>(row["PayTime"]);
            this._PayType = DataUtils.ConvertValue<string>(row["PayType"]);
            this._OperatorType = DataUtils.ConvertValue<string>(row["OperatorType"]);
            this._HelperId = DataUtils.ConvertValue<Guid?>(row["HelperId"]);
            this._Helper = DataUtils.ConvertValue<string>(row["Helper"]);
            this._OldHelper = DataUtils.ConvertValue<string>(row["OldHelper"]);
            this._OldHelperId = DataUtils.ConvertValue<Guid?>(row["OldHelperId"]);
            this._ExamRoomId = DataUtils.ConvertValue<Guid>(row["ExamRoomId"]);
            this._IsSure = DataUtils.ConvertValue<bool>(row["IsSure"]);
            this._SureTime = DataUtils.ConvertValue<DateTime?>(row["SureTime"]);
            this._SureHelper = DataUtils.ConvertValue<string>(row["SureHelper"]);
            this._Cost = DataUtils.ConvertValue<decimal>(row["Cost"]);
            this._RealCost = DataUtils.ConvertValue<decimal?>(row["RealCost"]);
            this._Discount = DataUtils.ConvertValue<decimal?>(row["Discount"]);
            this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
            this._ExamName = DataUtils.ConvertValue<string>(row["ExamName"]);
            this._State = DataUtils.ConvertValue<int>(row["State"]);
            this._PayCoachOperatorId = DataUtils.ConvertValue<Guid?>(row["PayCoachOperatorId"]);
            this._PayCoachOperator = DataUtils.ConvertValue<string>(row["PayCoachOperator"]);
            this._PayCoachTime = DataUtils.ConvertValue<DateTime?>(row["PayCoachTime"]);
            this._IsPayCoach = DataUtils.ConvertValue<bool>(row["IsPayCoach"]);
            this._IP = DataUtils.ConvertValue<string>(row["IP"]);
            this._IsPayHelper = DataUtils.ConvertValue<bool>(row["IsPayHelper"]);
            this._PayHelperTime = DataUtils.ConvertValue<DateTime?>(row["PayHelperTime"]);
            this._PayHelperOperator = DataUtils.ConvertValue<string>(row["PayHelperOperator"]);
            this._PayHelperOperatorId = DataUtils.ConvertValue<Guid?>(row["PayHelperOperatorId"]);
            this._RefundTime = DataUtils.ConvertValue<DateTime?>(row["RefundTime"]);
            this._RefundCost = DataUtils.ConvertValue<decimal?>(row["RefundCost"]);
            this._CallState = DataUtils.ConvertValue<int?>(row["CallState"]);
            this._GetOnTime = DataUtils.ConvertValue<DateTime?>(row["GetOnTime"]);
            this._SignInTime = DataUtils.ConvertValue<DateTime?>(row["SignInTime"]);
            this._PrintTime = DataUtils.ConvertValue<DateTime?>(row["PrintTime"]);
            this._PrintCount = DataUtils.ConvertValue<int>(row["PrintCount"]);
            this._AddPrintOpertor = DataUtils.ConvertValue<string>(row["AddPrintOpertor"]);
            this._AddPrintOpertorId = DataUtils.ConvertValue<Guid?>(row["AddPrintOpertorId"]);
            this._AddPrintOpertorTime = DataUtils.ConvertValue<DateTime?>(row["AddPrintOpertorTime"]);
            this._CoachName = DataUtils.ConvertValue<string>(row["CoachName"]);
            this._CoachId = DataUtils.ConvertValue<Guid?>(row["CoachId"]);
            this._SchoolName = DataUtils.ConvertValue<string>(row["SchoolName"]);
            this._SchoolId = DataUtils.ConvertValue<Guid?>(row["SchoolId"]);
            this._IsWeChartSure = DataUtils.ConvertValue<bool>(row["IsWeChartSure"]);
            this._WeChartSureTime = DataUtils.ConvertValue<DateTime?>(row["WeChartSureTime"]);
            this._CoachPMoney = DataUtils.ConvertValue<decimal>(row["CoachPMoney"]);
            this._HelperPMoney = DataUtils.ConvertValue<decimal>(row["HelperPMoney"]);
            this._OCoachPMoney = DataUtils.ConvertValue<decimal>(row["OCoachPMoney"]);
            this._CarPMoney = DataUtils.ConvertValue<decimal>(row["CarPMoney"]);
            this._CallTime = DataUtils.ConvertValue<DateTime?>(row["CallTime"]);
            this._IceFrozenTime = DataUtils.ConvertValue<DateTime?>(row["IceFrozenTime"]);
            this._AutoRemark = DataUtils.ConvertValue<string>(row["AutoRemark"]);
            this._GetOffTime = DataUtils.ConvertValue<DateTime?>(row["GetOffTime"]);
            this._NewSerialNumber = DataUtils.ConvertValue<string>(row["NewSerialNumber"]);
            this._RefundPrintTime = DataUtils.ConvertValue<DateTime?>(row["RefundPrintTime"]);
            this._RefundPrintOpertorId = DataUtils.ConvertValue<Guid?>(row["RefundPrintOpertorId"]);
            this._RefundPrintOpertor = DataUtils.ConvertValue<string>(row["RefundPrintOpertor"]);
            this._RefundPrintCount = DataUtils.ConvertValue<int>(row["RefundPrintCount"]);
            this._RefundOpertor = DataUtils.ConvertValue<string>(row["RefundOpertor"]);
            this._RefundOpertorId = DataUtils.ConvertValue<Guid?>(row["RefundOpertorId"]);
            this._RefundId = DataUtils.ConvertValue<Guid?>(row["RefundId"]);
            this._Fee = DataUtils.ConvertValue<decimal>(row["Fee"]);
            this._CancelTime = DataUtils.ConvertValue<DateTime?>(row["CancelTime"]);
            this._IsPutTop = DataUtils.ConvertValue<bool>(row["IsPutTop"]);
            this._PutTopTime = DataUtils.ConvertValue<DateTime?>(row["PutTopTime"]);
            this._PutTopOpertor = DataUtils.ConvertValue<string>(row["PutTopOpertor"]);
            this._PutTopOpertorId = DataUtils.ConvertValue<Guid?>(row["PutTopOpertorId"]);
            this._PaySchoolId = DataUtils.ConvertValue<Guid?>(row["PaySchoolId"]);
            this._PaySchool = DataUtils.ConvertValue<string>(row["PaySchool"]);
            this._CarChangeTime = DataUtils.ConvertValue<DateTime?>(row["CarChangeTime"]);
            this._ExpireRepairTime = DataUtils.ConvertValue<DateTime?>(row["ExpireRepairTime"]);
            this._ExpireRepairOpertor = DataUtils.ConvertValue<string>(row["ExpireRepairOpertor"]);
            this._ExpireRepairOpertorId = DataUtils.ConvertValue<Guid?>(row["ExpireRepairOpertorId"]);
            this._IsOverdue = DataUtils.ConvertValue<bool>(row["IsOverdue"]);
            this._OrderFrom = DataUtils.ConvertValue<string>(row["OrderFrom"]);
            this._IsEvaluate = DataUtils.ConvertValue<bool>(row["IsEvaluate"]);
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Biz_AnalogExam");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Biz_AnalogExam", "ID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BatchID = new Field("BatchID", "Biz_AnalogExam", "BatchID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SerialNumber = new Field("SerialNumber", "Biz_AnalogExam", "SerialNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Number = new Field("Number", "Biz_AnalogExam", "Number");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SortNumber = new Field("SortNumber", "Biz_AnalogExam", "SortNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Subject = new Field("Subject", "Biz_AnalogExam", "Subject");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SubjectValue = new Field("SubjectValue", "Biz_AnalogExam", "SubjectValue");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DrivingType = new Field("DrivingType", "Biz_AnalogExam", "DrivingType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PlanChildId = new Field("PlanChildId", "Biz_AnalogExam", "PlanChildId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CarId = new Field("CarId", "Biz_AnalogExam", "CarId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CarNumber = new Field("CarNumber", "Biz_AnalogExam", "CarNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OldCarId = new Field("OldCarId", "Biz_AnalogExam", "OldCarId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OldCarNumber = new Field("OldCarNumber", "Biz_AnalogExam", "OldCarNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CostId = new Field("CostId", "Biz_AnalogExam", "CostId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExamTime = new Field("ExamTime", "Biz_AnalogExam", "ExamTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExamTimeSpan = new Field("ExamTimeSpan", "Biz_AnalogExam", "ExamTimeSpan");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IDNumberTwo = new Field("IDNumberTwo", "Biz_AnalogExam", "IDNumberTwo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IDNumber = new Field("IDNumber", "Biz_AnalogExam", "IDNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Name = new Field("Name", "Biz_AnalogExam", "Name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field NameTwo = new Field("NameTwo", "Biz_AnalogExam", "NameTwo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WeChat = new Field("WeChat", "Biz_AnalogExam", "WeChat");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Phone = new Field("Phone", "Biz_AnalogExam", "Phone");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MobilePhoneTwo = new Field("MobilePhoneTwo", "Biz_AnalogExam", "MobilePhoneTwo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MobilePhone = new Field("MobilePhone", "Biz_AnalogExam", "MobilePhone");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OperatorId = new Field("OperatorId", "Biz_AnalogExam", "OperatorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Operator = new Field("Operator", "Biz_AnalogExam", "Operator");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayTime = new Field("PayTime", "Biz_AnalogExam", "PayTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayType = new Field("PayType", "Biz_AnalogExam", "PayType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OperatorType = new Field("OperatorType", "Biz_AnalogExam", "OperatorType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field HelperId = new Field("HelperId", "Biz_AnalogExam", "HelperId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Helper = new Field("Helper", "Biz_AnalogExam", "Helper");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OldHelper = new Field("OldHelper", "Biz_AnalogExam", "OldHelper");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OldHelperId = new Field("OldHelperId", "Biz_AnalogExam", "OldHelperId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExamRoomId = new Field("ExamRoomId", "Biz_AnalogExam", "ExamRoomId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsSure = new Field("IsSure", "Biz_AnalogExam", "IsSure");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SureTime = new Field("SureTime", "Biz_AnalogExam", "SureTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SureHelper = new Field("SureHelper", "Biz_AnalogExam", "SureHelper");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Cost = new Field("Cost", "Biz_AnalogExam", "Cost");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RealCost = new Field("RealCost", "Biz_AnalogExam", "RealCost");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Discount = new Field("Discount", "Biz_AnalogExam", "Discount");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreateTime = new Field("CreateTime", "Biz_AnalogExam", "CreateTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExamName = new Field("ExamName", "Biz_AnalogExam", "ExamName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field State = new Field("State", "Biz_AnalogExam", "State");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayCoachOperatorId = new Field("PayCoachOperatorId", "Biz_AnalogExam", "PayCoachOperatorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayCoachOperator = new Field("PayCoachOperator", "Biz_AnalogExam", "PayCoachOperator");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayCoachTime = new Field("PayCoachTime", "Biz_AnalogExam", "PayCoachTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsPayCoach = new Field("IsPayCoach", "Biz_AnalogExam", "IsPayCoach");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IP = new Field("IP", "Biz_AnalogExam", "IP");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsPayHelper = new Field("IsPayHelper", "Biz_AnalogExam", "IsPayHelper");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayHelperTime = new Field("PayHelperTime", "Biz_AnalogExam", "PayHelperTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayHelperOperator = new Field("PayHelperOperator", "Biz_AnalogExam", "PayHelperOperator");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayHelperOperatorId = new Field("PayHelperOperatorId", "Biz_AnalogExam", "PayHelperOperatorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundTime = new Field("RefundTime", "Biz_AnalogExam", "RefundTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundCost = new Field("RefundCost", "Biz_AnalogExam", "RefundCost");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CallState = new Field("CallState", "Biz_AnalogExam", "CallState");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GetOnTime = new Field("GetOnTime", "Biz_AnalogExam", "GetOnTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SignInTime = new Field("SignInTime", "Biz_AnalogExam", "SignInTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PrintTime = new Field("PrintTime", "Biz_AnalogExam", "PrintTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PrintCount = new Field("PrintCount", "Biz_AnalogExam", "PrintCount");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AddPrintOpertor = new Field("AddPrintOpertor", "Biz_AnalogExam", "AddPrintOpertor");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AddPrintOpertorId = new Field("AddPrintOpertorId", "Biz_AnalogExam", "AddPrintOpertorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AddPrintOpertorTime = new Field("AddPrintOpertorTime", "Biz_AnalogExam", "AddPrintOpertorTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CoachName = new Field("CoachName", "Biz_AnalogExam", "CoachName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CoachId = new Field("CoachId", "Biz_AnalogExam", "CoachId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SchoolName = new Field("SchoolName", "Biz_AnalogExam", "SchoolName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SchoolId = new Field("SchoolId", "Biz_AnalogExam", "SchoolId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsWeChartSure = new Field("IsWeChartSure", "Biz_AnalogExam", "IsWeChartSure");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WeChartSureTime = new Field("WeChartSureTime", "Biz_AnalogExam", "WeChartSureTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CoachPMoney = new Field("CoachPMoney", "Biz_AnalogExam", "CoachPMoney");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field HelperPMoney = new Field("HelperPMoney", "Biz_AnalogExam", "HelperPMoney");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OCoachPMoney = new Field("OCoachPMoney", "Biz_AnalogExam", "OCoachPMoney");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CarPMoney = new Field("CarPMoney", "Biz_AnalogExam", "CarPMoney");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CallTime = new Field("CallTime", "Biz_AnalogExam", "CallTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IceFrozenTime = new Field("IceFrozenTime", "Biz_AnalogExam", "IceFrozenTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AutoRemark = new Field("AutoRemark", "Biz_AnalogExam", "AutoRemark");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GetOffTime = new Field("GetOffTime", "Biz_AnalogExam", "GetOffTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field NewSerialNumber = new Field("NewSerialNumber", "Biz_AnalogExam", "NewSerialNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundPrintTime = new Field("RefundPrintTime", "Biz_AnalogExam", "RefundPrintTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundPrintOpertorId = new Field("RefundPrintOpertorId", "Biz_AnalogExam", "RefundPrintOpertorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundPrintOpertor = new Field("RefundPrintOpertor", "Biz_AnalogExam", "RefundPrintOpertor");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundPrintCount = new Field("RefundPrintCount", "Biz_AnalogExam", "RefundPrintCount");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundOpertor = new Field("RefundOpertor", "Biz_AnalogExam", "RefundOpertor");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundOpertorId = new Field("RefundOpertorId", "Biz_AnalogExam", "RefundOpertorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RefundId = new Field("RefundId", "Biz_AnalogExam", "RefundId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Fee = new Field("Fee", "Biz_AnalogExam", "Fee");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CancelTime = new Field("CancelTime", "Biz_AnalogExam", "CancelTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsPutTop = new Field("IsPutTop", "Biz_AnalogExam", "IsPutTop");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PutTopTime = new Field("PutTopTime", "Biz_AnalogExam", "PutTopTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PutTopOpertor = new Field("PutTopOpertor", "Biz_AnalogExam", "PutTopOpertor");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PutTopOpertorId = new Field("PutTopOpertorId", "Biz_AnalogExam", "PutTopOpertorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PaySchoolId = new Field("PaySchoolId", "Biz_AnalogExam", "PaySchoolId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PaySchool = new Field("PaySchool", "Biz_AnalogExam", "PaySchool");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CarChangeTime = new Field("CarChangeTime", "Biz_AnalogExam", "CarChangeTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExpireRepairTime = new Field("ExpireRepairTime", "Biz_AnalogExam", "ExpireRepairTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExpireRepairOpertor = new Field("ExpireRepairOpertor", "Biz_AnalogExam", "ExpireRepairOpertor");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExpireRepairOpertorId = new Field("ExpireRepairOpertorId", "Biz_AnalogExam", "ExpireRepairOpertorId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsOverdue = new Field("IsOverdue", "Biz_AnalogExam", "IsOverdue");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OrderFrom = new Field("OrderFrom", "Biz_AnalogExam", "OrderFrom");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsEvaluate = new Field("IsEvaluate", "Biz_AnalogExam", "IsEvaluate");
        }
        #endregion


    }
}

