//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//     Support: http://www.cnblogs.com/huxj
//     Website: http://www.ITdos.com/
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

    /// <summary>
    /// 实体类O2O_RecruitmentCoach 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public partial class O2O_RecruitmentCoach : Entity
    {
        public O2O_RecruitmentCoach() : base("O2O_RecruitmentCoach") { }

        #region Model
        private string _id;
        private DateTime _create_time;
        private DateTime _update_time;
        private string _real_name;
        private string _phone;
        private string _address;
        private string _intro;
        private int _status;
        /// <summary>
        /// 
        /// </summary>
        public string id
        {
            get { return _id; }
            set
            {
                this.OnPropertyValueChange(_.id, _id, value);
                this._id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime create_time
        {
            get { return _create_time; }
            set
            {
                this.OnPropertyValueChange(_.create_time, _create_time, value);
                this._create_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime update_time
        {
            get { return _update_time; }
            set
            {
                this.OnPropertyValueChange(_.update_time, _update_time, value);
                this._update_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string real_name
        {
            get { return _real_name; }
            set
            {
                this.OnPropertyValueChange(_.real_name, _real_name, value);
                this._real_name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string phone
        {
            get { return _phone; }
            set
            {
                this.OnPropertyValueChange(_.phone, _phone, value);
                this._phone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string address
        {
            get { return _address; }
            set
            {
                this.OnPropertyValueChange(_.address, _address, value);
                this._address = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string intro
        {
            get { return _intro; }
            set
            {
                this.OnPropertyValueChange(_.intro, _intro, value);
                this._intro = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int status
        {
            get { return _status; }
            set
            {
                this.OnPropertyValueChange(_.status, _status, value);
                this._status = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.create_time,
				_.update_time,
				_.real_name,
				_.phone,
				_.address,
				_.intro,
				_.status};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._create_time,
				this._update_time,
				this._real_name,
				this._phone,
				this._address,
				this._intro,
				this._status};
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(IDataReader reader)
        {
            this._id = DataUtils.ConvertValue<string>(reader["id"]);
            this._create_time = DataUtils.ConvertValue<DateTime>(reader["create_time"]);
            this._update_time = DataUtils.ConvertValue<DateTime>(reader["update_time"]);
            this._real_name = DataUtils.ConvertValue<string>(reader["real_name"]);
            this._phone = DataUtils.ConvertValue<string>(reader["phone"]);
            this._address = DataUtils.ConvertValue<string>(reader["address"]);
            this._intro = DataUtils.ConvertValue<string>(reader["intro"]);
            this._status = DataUtils.ConvertValue<int>(reader["status"]);
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(DataRow row)
        {
            this._id = DataUtils.ConvertValue<string>(row["id"]);
            this._create_time = DataUtils.ConvertValue<DateTime>(row["create_time"]);
            this._update_time = DataUtils.ConvertValue<DateTime>(row["update_time"]);
            this._real_name = DataUtils.ConvertValue<string>(row["real_name"]);
            this._phone = DataUtils.ConvertValue<string>(row["phone"]);
            this._address = DataUtils.ConvertValue<string>(row["address"]);
            this._intro = DataUtils.ConvertValue<string>(row["intro"]);
            this._status = DataUtils.ConvertValue<int>(row["status"]);
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "O2O_RecruitmentCoach");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field id = new Field("id", "O2O_RecruitmentCoach", "id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field create_time = new Field("create_time", "O2O_RecruitmentCoach", "create_time");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field update_time = new Field("update_time", "O2O_RecruitmentCoach", "update_time");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field real_name = new Field("real_name", "O2O_RecruitmentCoach", "real_name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field phone = new Field("phone", "O2O_RecruitmentCoach", "phone");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field address = new Field("address", "O2O_RecruitmentCoach", "address");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field intro = new Field("intro", "O2O_RecruitmentCoach", "intro");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field status = new Field("status", "O2O_RecruitmentCoach", "status");
        }
        #endregion


    }
}

