//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19132
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

    /// <summary>
    /// 实体类O2O_CourseRelationCoach 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public partial class O2O_CourseRelationCoach : Entity
    {
        public O2O_CourseRelationCoach() : base("O2O_CourseRelationCoach") { }

        #region Model
        private string _id;
        private DateTime _create_time;
        private DateTime _update_time;
        private string _user_id;
        private Guid _CoachId;
        private string _course_id;
        /// <summary>
        /// 
        /// </summary>
        public string id
        {
            get { return _id; }
            set
            {
                this.OnPropertyValueChange(_.id, _id, value);
                this._id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime create_time
        {
            get { return _create_time; }
            set
            {
                this.OnPropertyValueChange(_.create_time, _create_time, value);
                this._create_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime update_time
        {
            get { return _update_time; }
            set
            {
                this.OnPropertyValueChange(_.update_time, _update_time, value);
                this._update_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string user_id
        {
            get { return _user_id; }
            set
            {
                this.OnPropertyValueChange(_.user_id, _user_id, value);
                this._user_id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid CoachId
        {
            get { return _CoachId; }
            set
            {
                this.OnPropertyValueChange(_.CoachId, _CoachId, value);
                this._CoachId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string course_id
        {
            get { return _course_id; }
            set
            {
                this.OnPropertyValueChange(_.course_id, _course_id, value);
                this._course_id = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.create_time,
				_.update_time,
				_.user_id,
				_.CoachId,
				_.course_id};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._create_time,
				this._update_time,
				this._user_id,
				this._CoachId,
				this._course_id};
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(IDataReader reader)
        {
            this._id = DataUtils.ConvertValue<string>(reader["id"]);
            this._create_time = DataUtils.ConvertValue<DateTime>(reader["create_time"]);
            this._update_time = DataUtils.ConvertValue<DateTime>(reader["update_time"]);
            this._user_id = DataUtils.ConvertValue<string>(reader["user_id"]);
            this._CoachId = DataUtils.ConvertValue<Guid>(reader["CoachId"]);
            this._course_id = DataUtils.ConvertValue<string>(reader["course_id"]);
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(DataRow row)
        {
            this._id = DataUtils.ConvertValue<string>(row["id"]);
            this._create_time = DataUtils.ConvertValue<DateTime>(row["create_time"]);
            this._update_time = DataUtils.ConvertValue<DateTime>(row["update_time"]);
            this._user_id = DataUtils.ConvertValue<string>(row["user_id"]);
            this._CoachId = DataUtils.ConvertValue<Guid>(row["CoachId"]);
            this._course_id = DataUtils.ConvertValue<string>(row["course_id"]);
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "O2O_CourseRelationCoach");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field id = new Field("id", "O2O_CourseRelationCoach", "id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field create_time = new Field("create_time", "O2O_CourseRelationCoach", "create_time");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field update_time = new Field("update_time", "O2O_CourseRelationCoach", "update_time");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field user_id = new Field("user_id", "O2O_CourseRelationCoach", "user_id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CoachId = new Field("CoachId", "O2O_CourseRelationCoach", "CoachId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field course_id = new Field("course_id", "O2O_CourseRelationCoach", "course_id");
        }
        #endregion


    }
}

