//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrmTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public System.Guid ID { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string c5 { get; set; }
        public string c6 { get; set; }
        public string c7 { get; set; }
        public string c8 { get; set; }
        public Nullable<long> c9 { get; set; }
        public string c10 { get; set; }
        public string c11 { get; set; }
        public Nullable<decimal> c12 { get; set; }
        public string c13 { get; set; }
        public Nullable<System.Guid> c14 { get; set; }
        public Nullable<int> c15 { get; set; }
        public Nullable<bool> c16 { get; set; }
        public string c17 { get; set; }
        public Nullable<System.DateTime> c18 { get; set; }
        public Nullable<double> c19 { get; set; }
        public string c20 { get; set; }
    }
}
